### PR TITLE
Blosc aws s3 improvement chris slater

### PR DESCRIPTION
**Pull request by SabineEmbacher**

### CODE REVIEW

**Comment by SabineEmbacher** [comment]
Thanks a lot to Chris Slater

**Comment by joshmoore** [comment]
Hi @SabineEmbacher. Is it worth testing out the state of the AWS S3 work or are there any blockers?

**Comment by SabineEmbacher** [comment]
With the latest changes I haven't done a test with real AWS S3 environment yet. Would not be bad if someone has time to test this. Maybe then another problem will show up that hasn't been covered in unit level tests yet.

Please note, JZarr itself does not connect to AWS S3, but here is an example that shows how it can be done.
https://jzarr.readthedocs.io/en/latest/amazonS3.html

Instead of LasersonLab's library, you can of course use another library that fully implements java.nio.file.FileSystem.

**Comment by joshmoore** [comment]
I'll put it on the list to try out! Do you foresee (eventually) having autodetection in jzarr itself similar to fsspec?

**Comment by SabineEmbacher** [comment]
Dear Josh,

> Do you foresee (eventually) having autodetection in jzarr itself similar to fsspec?

I'm afraid I don't understand what you mean.

What should be detected automatically?
A detection, to which cloud computing service the FileSystemStore shall connect?

If yes ... No, that is not planed, because then we every time have to change the JZarr library, in case of service API changes or if new services are available. The second point is that we want to be tied to other libraries as less as possible. This often causes problems e.g. if we are bound to 2 libraries which both has dependencies to the same third library but to different versions e.g. v2.4 and v3.1 which can cause conflicts.

Since we don't have a maintenance contract to react on external changes and to follow library changes our plan is to leave it up to the user to decide to which service (local or remote) they want to connect to. Also the way how they want to connect to, if with own code or using a library. Also which library and version they want to use for that connection.
If there exist e.g. 3 Libraries to connect to the same service (e.g. AWS S3) then the user can do its own tests to find out the library which best matches to user needs.

JZarr shall focus on reading and writing zarr data independent to the used filesystem.

Best Regards
Sabine

**Comment by joshmoore** [comment]
> JZarr shall focus on reading and writing zarr data independent to the used filesystem.

Understood. Thanks for the explanation!
~J.

**Pull request merged**
